### ISSUE TITLE
Alias Error on iOS

### ISSUE THREAD

**Issue by nsarakas** [KhalidWar/anonaddy#83]
I am seeing the following when I try to create a new alias:
![image](https://github.com/KhalidWar/anonaddy/assets/2875949/49b4e1c2-7042-4410-a633-60729f0bcae5)

I have a self hosted instance. My alias is set to random words and I do have a default domain selected. I can create new aliases via the web portal just fine. I did also notice when I select any of my domains in the app, it tells me:
![image](https://github.com/KhalidWar/anonaddy/assets/2875949/f5f3f089-ebf3-4b52-b175-484f144d8f45)
In the web version, it shows all domains have verified records. Not sure if these are related issues or two separate issues.

I have tried the following:
- sign out and back in
- delete and reinstall the app
- create new API key

Via the app, in the past I was able to generate new aliases on the fly but I cannot say when it stopped. In app, it says I am running version 1.0, but the AppStore shows 2.9.2 is installed.

**Comment by KhalidWar** [comment]
Thanks for reporting this issue. Yes, alias and domain are 2 separate issues.

I can't reproduce the alias bug but I think it's because your self-hosted instance isn't up to date and it is missing data which is causing AddyManager to fail. 

`v1.0.0 App Version` refers to your self hosted instance's version. @anonaddy has a self hosted intaces that I use for testing and it shows `v1.1.0` but `About App` points to AddyManager's details and its latest version is 2.9.2. I'm sorry but I should have made this clearer in the app. Will fix next update.

### **Can you update to instance and see if this issue persists?**

![F175EFEE-C36C-43F4-836C-D86470D837A1_1_201_a](https://github.com/KhalidWar/anonaddy/assets/49177109/1fcb53a6-1531-4d88-a22e-97e31a6eef3b)

Regarding domains, the whole feature is still `beta` as I'm slowly working on improving the UI and handling edge cases. In the meantime, please use the web portal as I resolve these issues.

**Comment by nsarakas** [comment]
Sweet sauce. Updating fixed the issue with new aliases. I am now on v1.1.0 on box and in app. I also re-enabled notifications of new Addy versions in GitHub. 😅

The domains is a nothing burger; I just wanted to make sure to call it out in case they were related. I only noticed it while troubleshooting on my end.

Thanks for the help! I can go back to my DevOps box now. 😂

**Comment by Gitchick57** [comment]
Is it me or is there no APK file on GitHub to download the app?  Why is that?



Apr 5, 2024, 4:40 PM by ***@***.***:

**Comment by KhalidWar** [comment]
> Is it me or is there no APK file on GitHub to download the app?  Why is that? Apr 5, 2024, 4:40 PM by ***@***.***:

@Gitchick57  Google Play Store and Apple App Store are the only supported distribution channels for various reasons. Mainly because AnonAddy's API and AddyManager are always evolving, and old stale versions may not work properly. So, providing standalone APKs with no direct channel to update to most current version isn't a good move. This issue is prime example of that. 

> Sweet sauce. Updating fixed the issue with new aliases. I am now on v1.1.0 on box and in app. I also re-enabled notifications of new Addy versions in GitHub. 😅

Awesome! I'm glad it worked. I will see if I can add in-app notification to let self-hosted instance users know when there's a new version. 

> Thanks for the help! I can go back to my DevOps box now. 😂

Of course you're in dev op 😂😂

**Comment by Gitchick57** [comment]
Thanks for the reply.  I like to download as many Android apps as possible via GitHub is all.



Apr 5, 2024, 5:40 PM by ***@***.***:
